### ISSUE TITLE
マッチした相手とメッセージできる機能

### ISSUE THREAD

**Issue by zukako0930** [zukako0930/matching_project#1]

**Comment by yuyurun** [comment]
- [ ] 送信者受信者の値渡し
- [ ] messageコントローラで処理
- [ ] モデルで送信者受信者を判定したメッセージの表示
- [ ] view(index)で表示
- [ ] 送信者受信者の表示の変化

**Comment by yuyurun** [comment]
- [ ] メッセージのフォーム

**Comment by yuyurun** [comment]
**やったこと**
userのshowのmatchersから、messageのindexに画面遷移
send_idとreceive_idを渡して、絞り込んで表示
indexの投稿フォームからmessage.newで投稿
indexに戻ってくる

**Comment by yuyurun** [comment]
# 今後
メッセージを送りあっているユーザー二人のうち、自分の方はセッションによって保持しているので、相手のidだけ渡せば良い
でも、今回はログイン機能マージ前に実装してので、両方渡している
後から、相手のidだけにしてもいい

**Comment by zukako0930** [comment]
別のissueにしてもいいかもね

**Comment by yuyurun** [comment]
なるほど！じゃあ、これはこれでcloseして新しいissue作りますね

**Comment by yuyurun** [comment]
メッセージの表示・投稿の動作確認ができたのでclose
