### ISSUE TITLE
メッセージできる機能の修正

### ISSUE THREAD

**Issue by yuyurun** [zukako0930/matching_project#12]
メッセージを送りあっているユーザー二人のうち、自分の方はセッションによって保持しているので、相手のidだけ渡せば良い
しかし、現在はログイン機能マージ前に実装してので、両方渡している

渡すのは、相手のidだけでも実装可能なので、修正

**Comment by zukako0930** [comment]
とりあえず修正したのでclose
何かバグが起きたらまた別のissueを立てる。
