### ISSUE TITLE
マッチしている人にマッチリクエストを送れないようにする

### ISSUE THREAD

**Issue by yuyurun** [zukako0930/matching_project#18]
# Why
すでにマッチしている人にもう１度マッチリクエスト送ってしまうと、メッセージに飛ぶボタンが２つ出てきてしまう

# How
マッチリクエスト自体を重複しないようにする
or
target_user_listにマッチした人は出さないようにする

**Comment by zukako0930** [comment]
target_user_listにマッチした人を表示しない方向で解決したのでclose
