### ISSUE TITLE
画像のアップロード機能と表示

### ISSUE THREAD

**Issue by zukako0930** [zukako0930/matching_project#4]
# why
マッチングには画像が必要不可欠
# フロー
- [x] userのカラムに画像ファイルのカラム:stringを追加
- [x] 画像をweb上に表示する。
- [x] 画像のアップロードをできるようにする。

**Comment by yuyurun** [comment]
gemとデータベースを変更しました。（bundle install , rails db:migrate）

**Comment by yuyurun** [comment]
# やったこと
- gem 'carrierwave' , gem 'rmagick'  gemのインストール
- userにimageカラムの追加
- アップローダーの作成

**Comment by yuyurun** [comment]
画像のアップロードと表示が共に動作確認OKだったのでclose
